version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.apache.maven:maven-artifact
    versions:
    - ">= 3.9"
  - dependency-name: org.apache.maven:maven-compat
    versions:
    - ">= 3.9"
  - dependency-name: org.apache.maven:maven-core
    versions:
    - ">= 3.9"
  - dependency-name: org.apache.maven:maven-model
    versions:
    - ">= 3.9"
  - dependency-name: org.apache.maven:maven-model-builder
    versions:
    - ">= 3.9"
  - dependency-name: org.apache.maven:maven-plugin-api
    versions:
    - ">= 3.9"
  - dependency-name: org.apache.maven:maven-repository-metadata
    versions:
    - ">= 3.9"
  - dependency-name: org.apache.maven:maven-settings
    versions:
    - ">= 3.9"
  - dependency-name: org.jetbrains.dokka:dokka-maven-plugin
    versions:
    - 1.4.20-dev-65
  - dependency-name: org.dom4j:dom4j
    versions:
    - ">= 2.2.0"
  - dependency-name: org.codehaus.plexus:plexus-xml
    versions:
    - ">= 4.1"
  - dependency-name: org.codehaus.plexus:plexus-classworlds
    versions:
    - ">= 2.10"
  - dependency-name: org.apache.maven.plugin-testing:maven-plugin-testing-harness
    versions:
    - ">= 3.4.0"
  - dependency-name: org.apache.maven.reporting:maven-reporting-impl
    versions:
    - ">= 4"
  - dependency-name: com.google.inject:guice
    versions:
    - ">= 5"
  - dependency-name: com.github.hboutemy:doxia-sink-api-ktx
    versions:
    - ">= 1.7.0"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
- package-ecosystem: devcontainers
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
