###
# #%L
# ktlint-maven-plugin
# %%
# Copyright (C) 2018 - 2022 GantSign Ltd.
# %%
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
# #L%
###
name: Maven deploy
on:
  workflow_call:
env:
  JAVA_TOOL_OPTIONS: >-
    -XX:TieredStopAtLevel=1
    -XX:+UseParallelGC

jobs:
  deploy:
    name: Maven deploy
    runs-on: ubuntu-20.04
    if: github.repository == 'gantsign/ktlint-maven-plugin'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          gpg-private-key: ${{ secrets.GPG_KEY }}
          server-id: ossrh
          server-username: OSSRH_USER
          server-password: OSSRH_TOKEN
      - name: Cache local Maven repository
        uses: gantsign/maven-periodic-cache-action@v1
        with:
          key-suffix: '-deploy'
          additional-path: '!~/.m2/repository/com/github/gantsign/maven'
      - name: Deploy with Maven
        run: |
          ./mvnw deploy \
              -P publish-artifacts,sign-artifacts,ossrh-deploy \
              -DskipTests \
              -Dinvoker.skip=true \
              --batch-mode \
              --show-version \
              -Dstyle.color=always
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
