name: Maven deploy
on:
  workflow_call:
env:
  JAVA_TOOL_OPTIONS: >-
    -XX:TieredStopAtLevel=1
    -XX:+UseParallelGC
    -Dstyle.color=always
    -Djansi.force=true

jobs:
  deploy:
    name: Maven deploy
    runs-on: ubuntu-20.04
    if: github.repository == 'gantsign/ktlint-maven-plugin'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
      # Since code changes to this project are infrequent, and most commits
      # change the pom.xml, we cache by date interval rather than file hash.
      - name: Calculate cache interval
        run: |
          leveler="$(wc -c <<< "$GITHUB_REPOSITORY")"
          echo "::set-output name=CACHE_INTERVAL::$(date +%Y)-$(($(($leveler + $(date +%-j))) / 30))"
        id: cache-interval
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/com/github/gantsign/maven
          key: ${{ runner.os }}-maven-${{ steps.cache-interval.outputs.CACHE_INTERVAL }}-deploy
          restore-keys: |
            ${{ runner.os }}-maven-${{ steps.cache-interval.outputs.CACHE_INTERVAL }}
      - name: Install GPG key
        run: |-
          gpg --batch --import-options import-show --import << EOF
          ${{ secrets.GPG_KEY }}
          EOF
      - name: Deploy with Maven
        run: .github/scripts/deploy.sh
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete GPG secret key
        if: ${{ always() }}
        run: gpg --batch --yes --delete-secret-keys ${{ secrets.GPG_KEY_NAME }} || true
      - name: Delete GPG public key
        if: ${{ always() }}
        run: gpg --batch --yes --delete-keys ${{ secrets.GPG_KEY_NAME }}
