name: Maven deploy
on:
  workflow_call:
env:
  JAVA_TOOL_OPTIONS: >-
    -XX:TieredStopAtLevel=1
    -XX:+UseParallelGC
    -Dstyle.color=always
    -Djansi.force=true

jobs:
  deploy:
    name: Maven deploy
    runs-on: ubuntu-20.04
    if: github.repository == 'gantsign/ktlint-maven-plugin'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
          gpg-private-key: ${{ secrets.GPG_KEY }}
      - name: Cache local Maven repository
        uses: gantsign/maven-periodic-cache-action@v1
        with:
          key-suffix: '-deploy'
          additional-path: '!~/.m2/repository/com/github/gantsign/maven'
      - name: Deploy with Maven
        run: |
          ./mvnw deploy \
              --settings .github/maven/settings.xml \
              -P publish-artifacts,sign-artifacts,ossrh-deploy \
              -DskipTests \
              -Dinvoker.skip=true \
              --batch-mode \
              --show-version
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
