name: Maven build
on:
  workflow_call:
env:
  JAVA_TOOL_OPTIONS: >-
    -XX:TieredStopAtLevel=1
    -XX:+UseParallelGC
    -Dstyle.color=always
    -Djansi.force=true

jobs:
  build:
    name: Maven build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        maven-version:
          - '3.3.9'
          - '3.6.1'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Cache local Maven repository
        uses: gantsign/maven-periodic-cache-action@v1
        with:
          additional-path: '!~/.m2/repository/com/github/gantsign/maven'
      - name: Build with Maven
        run: .github/scripts/build.sh
        env:
          MAVEN_VERSION: ${{ matrix.maven-version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Code coverage report
        if: matrix.maven-version == '3.6.1'
        uses: codecov/codecov-action@v3.1.0
