name: Release
on:
  push:
    tags:
      - '*'
env:
  JAVA_TOOL_OPTIONS: >-
    -XX:TieredStopAtLevel=1
    -XX:+UseParallelGC
    -Dstyle.color=always
    -Djansi.force=true

jobs:
  build:
    name: Maven build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        maven-version:
          - '3.3.9'
          - '3.6.1'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: .github/scripts/build.sh
        env:
          MAVEN_VERSION: ${{ matrix.maven-version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Code coverage report
        if: matrix.maven-version == '3.6.1'
        uses: codecov/codecov-action@v1

  build-all:
    if: ${{ always() }}
    name: Build (matrix)
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: Check build matrix status
        run: "[[ '${{ needs.build.result }}' == 'success' ]] || exit 1"

  deploy:
    name: Maven deploy
    runs-on: ubuntu-18.04
    if: github.repository == 'gantsign/ktlint-maven-plugin'
    needs: build-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Install GPG key
        run: |-
          gpg --batch --import-options import-show --import << EOF
          ${{ secrets.GPG_KEY }}
          EOF
      - name: Deploy with Maven
        run: .github/scripts/deploy.sh
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete GPG secret key
        if: ${{ always() }}
        run: gpg --batch --yes --delete-secret-keys ${{ secrets.GPG_KEY_NAME }} || true
      - name: Delete GPG public key
        if: ${{ always() }}
        run: gpg --batch --yes --delete-keys ${{ secrets.GPG_KEY_NAME }}

  deploy-site:
    name: Maven deploy site
    runs-on: ubuntu-18.04
    if: github.repository == 'gantsign/ktlint-maven-plugin'
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Configure Git user
        run: >-
          git config --global user.name 'John Freeman' &&
          git config --global user.email '17984707+freemanjp@users.noreply.github.com'
      - name: Deploy Maven site
        run: .github/scripts/deploy-site.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
