name: Release
on:
  release:
    types:
      - published
env:
  JAVA_TOOL_OPTIONS: >-
    -XX:TieredStopAtLevel=1
    -XX:+UseParallelGC
    -Dstyle.color=always
    -Djansi.force=true

jobs:
  build:
    name: Build
    uses: './.github/workflows/maven-build.yml'

  deploy:
    name: Deploy
    needs: build
    uses: './.github/workflows/maven-deploy.yml'
    secrets: inherit

  deploy-site:
    name: Maven deploy site
    runs-on: ubuntu-20.04
    if: github.repository == 'gantsign/ktlint-maven-plugin'
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Cache local Maven repository
        uses: gantsign/maven-periodic-cache-action@v1
        with:
          additional-path: '!~/.m2/repository/com/github/gantsign/maven'
      - name: Configure Git user
        run: >-
          git config --global user.name 'John Freeman' &&
          git config --global user.email '17984707+freemanjp@users.noreply.github.com'
      - name: Deploy Maven site
        run: .github/scripts/deploy-site.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
