###
# #%L
# ktlint-maven-plugin
# %%
# Copyright (C) 2018 - 2022 GantSign Ltd.
# %%
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
# #L%
###
name: Release
on:
  release:
    types:
      - published
env:
  JAVA_TOOL_OPTIONS: >-
    -XX:TieredStopAtLevel=1
    -XX:+UseParallelGC

jobs:
  build:
    name: Build
    uses: './.github/workflows/maven-build.yml'

  deploy:
    name: Deploy
    needs: build
    uses: './.github/workflows/maven-deploy.yml'
    secrets: inherit

  deploy-site:
    name: Maven deploy site
    runs-on: ubuntu-20.04
    if: github.repository == 'gantsign/ktlint-maven-plugin'
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Cache local Maven repository
        uses: gantsign/maven-periodic-cache-action@v1
        with:
          key-suffix: '-deploy-site'
          additional-path: '!~/.m2/repository/com/github/gantsign/maven'
      - name: Configure Git user
        run: >-
          git config --global user.name 'John Freeman' &&
          git config --global user.email '17984707+freemanjp@users.noreply.github.com'
      - name: Build Maven site
        run: |
          ./mvnw site \
              -DskipTests \
              -Dinvoker.skip=true \
              --batch-mode \
              --show-version \
              -Dstyle.color=always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Stage Maven site
        run: |
          ./mvnw site:stage \
              -DskipTests \
              -Dinvoker.skip=true \
              --batch-mode \
              -Dstyle.color=always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy Maven site
        run: |
          ./mvnw scm-publish:publish-scm \
              -P gh-pages \
              -DskipTests \
              -Dinvoker.skip=true \
              --batch-mode \
              -Dstyle.color=always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
